name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    steps:
      - run: sudo apt update -y && sudo apt install git yarn node
